// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY9RKLaW6ngSCHvQqiujNxpRwJ9kzssgU',
    appId: '1:368198382683:web:1c00691fe118faa041fb7e',
    messagingSenderId: '368198382683',
    projectId: 'zpos-d985c',
    authDomain: 'zpos-d985c.firebaseapp.com',
    databaseURL: 'https://zpos-d985c-default-rtdb.firebaseio.com',
    storageBucket: 'zpos-d985c.firebasestorage.app',
  );

  // Secondary Firebase project — Jobs_done & Jobs_completed live here
  static const FirebaseOptions forthWeb = FirebaseOptions(
    apiKey: 'AIzaSyCdITzOwEzJ0S3BxeiFWzJyG_QeetguJeU',
    appId: '1:622437507678:web:4a0230dabb6e6161d5cacf',
    messagingSenderId: '622437507678',
    projectId: 'signuptest-53277',
    authDomain: 'signuptest-53277.firebaseapp.com',
    storageBucket: 'signuptest-53277.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn9Dmm_W9HNsbOj6K8RApfCf7zP4bfriI',
    appId: '1:368198382683:android:124fadc4511c30ef41fb7e',
    messagingSenderId: '368198382683',
    projectId: 'zpos-d985c',
    databaseURL: 'https://zpos-d985c-default-rtdb.firebaseio.com',
    storageBucket: 'zpos-d985c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdT_kzyD7LfuukVi0CX4QhGRu7HCF5Oc',
    appId: '1:368198382683:ios:97d0094bfe871a3141fb7e',
    messagingSenderId: '368198382683',
    projectId: 'zpos-d985c',
    databaseURL: 'https://zpos-d985c-default-rtdb.firebaseio.com',
    storageBucket: 'zpos-d985c.firebasestorage.app',
    iosBundleId: 'com.example.washkolangcustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEdT_kzyD7LfuukVi0CX4QhGRu7HCF5Oc',
    appId: '1:368198382683:ios:97d0094bfe871a3141fb7e',
    messagingSenderId: '368198382683',
    projectId: 'zpos-d985c',
    databaseURL: 'https://zpos-d985c-default-rtdb.firebaseio.com',
    storageBucket: 'zpos-d985c.firebasestorage.app',
    iosBundleId: 'com.example.washkolangcustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY9RKLaW6ngSCHvQqiujNxpRwJ9kzssgU',
    appId: '1:368198382683:web:cca8e71a1cd1d1b841fb7e',
    messagingSenderId: '368198382683',
    projectId: 'zpos-d985c',
    authDomain: 'zpos-d985c.firebaseapp.com',
    databaseURL: 'https://zpos-d985c-default-rtdb.firebaseio.com',
    storageBucket: 'zpos-d985c.firebasestorage.app',
  );
}
